Repository r-lib/lintr, pull requests merged in 2022-10, with the labels that each got.

#1568 New lengths_linter
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/lengths_linter.R
  inst/lintr/linters.csv
  man/best_practices_linters.Rd
  man/efficiency_linters.Rd
  man/lengths_linter.Rd
  man/linters.Rd
  man/readability_linters.Rd
  tests/testthat/test-lengths_linter.R
Labels: google-linters

#1579 New boolean_arithmetic_linter
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/boolean_arithmetic_linter.R
  inst/lintr/linters.csv
  man/best_practices_linters.Rd
  man/boolean_arithmetic_linter.Rd
  man/efficiency_linters.Rd
  man/linters.Rd
  man/readability_linters.Rd
  tests/testthat/test-boolean_arithmetic_linter.R
Labels: google-linters

#1612 improve handling of glued object extraction
  R/object_usage_linter.R
  tests/testthat/test-object_usage_linter.R
Labels: performance

#1637 New empty_assignment_linter
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/empty_assignment_linter.R
  inst/lintr/linters.csv
  man/best_practices_linters.Rd
  man/empty_assignment_linter.Rd
  man/linters.Rd
  man/readability_linters.Rd
  tests/testthat/test-empty_assignment_linter.R
Labels: google-linters

#1646 Use {withr} more comprehensively in tests to manage state
  tests/testthat.R
  tests/testthat/helper.R
  tests/testthat/test-backport_linter.R
  tests/testthat/test-cache.R
  tests/testthat/test-checkstyle_output.R
  tests/testthat/test-get_source_expressions.R
  tests/testthat/test-lint_file.R
  tests/testthat/test-lint_package.R
  tests/testthat/test-methods.R
  tests/testthat/test-normalize_exclusions.R
  tests/testthat/test-parse_exclusions.R
  tests/testthat/test-settings.R
Labels: internals

#1635 New is_numeric_linter
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/is_numeric_linter.R
  inst/lintr/linters.csv
  man/best_practices_linters.Rd
  man/consistency_linters.Rd
  man/is_numeric_linter.Rd
  man/linters.Rd
  man/readability_linters.Rd
  tests/testthat/test-is_numeric_linter.R
Labels: google-linters

#1652 extend paste_linter() for strrep() equivalents
  NEWS.md
  R/paste_linter.R
  man/paste_linter.Rd
  tests/testthat/test-paste_linter.R
Labels: google-linters

#1658 coverage test of xml_nodes_to_lints
  tests/testthat/test-xml_nodes_to_lints.R
Labels: testing

#1664 Add examples to documentation: Part-6 (o-p)
  R/assignment_linter.R
  R/brace_linter.R
  R/empty_assignment_linter.R
  R/function_return_linter.R
  R/infix_spaces_linter.R
  R/object_name_linters.R
  R/object_usage_linter.R
  R/outer_negation_linter.R
  R/package_hooks_linter.R
  R/paren_body_linter.R
  R/paste_linter.R
  R/pipe_call_linter.R
  R/pipe_continuation_linter.R
  man/assignment_linter.Rd
  man/brace_linter.Rd
  man/empty_assignment_linter.Rd
  man/function_return_linter.Rd
  man/infix_spaces_linter.Rd
  man/object_length_linter.Rd
  man/object_name_linter.Rd
  man/object_usage_linter.Rd
  man/outer_negation_linter.Rd
  man/package_hooks_linter.Rd
  man/paren_body_linter.Rd
  man/paste_linter.Rd
  man/pipe_call_linter.Rd
  man/pipe_continuation_linter.Rd
  tests/testthat/test-object_length_linter.R
  tests/testthat/test-object_name_linter.R
  tests/testthat/test-outer_negation_linter.R
  tests/testthat/test-paste_linter.R
  tests/testthat/test-pipe_call_linter.R
Labels: documentation

#1666 friendlier input validation, coverage in undesirable_operator_linter
  R/undesirable_operator_linter.R
  tests/testthat/test-undesirable_operator_linter.R
Labels: testing

#1674 Add examples to documentation: Part-7 (q-s)
  R/function_left_parentheses_linter.R
  R/redundant_equals_linter.R
  R/redundant_ifelse_linter.R
  R/regex_subset_linter.R
  R/semicolon_linter.R
  R/seq_linter.R
  R/single_quotes_linter.R
  R/spaces_inside_linter.R
  R/spaces_left_parentheses_linter.R
  R/sprintf_linter.R
  R/string_boundary_linter.R
  R/strings_as_factors_linter.R
  R/system_file_linter.R
  man/function_left_parentheses_linter.Rd
  man/redundant_equals_linter.Rd
  man/redundant_ifelse_linter.Rd
  man/regex_subset_linter.Rd
  man/semicolon_linter.Rd
  man/seq_linter.Rd
  man/single_quotes_linter.Rd
  man/spaces_inside_linter.Rd
  man/spaces_left_parentheses_linter.Rd
  man/sprintf_linter.Rd
  man/string_boundary_linter.Rd
  man/strings_as_factors_linter.Rd
  man/system_file_linter.Rd
  tests/testthat/test-redundant_equals_linter.R
  tests/testthat/test-redundant_ifelse_linter.R
  tests/testthat/test-regex_subset_linter.R
  tests/testthat/test-spaces_inside_linter.R
  tests/testthat/test-spaces_left_parentheses_linter.R
  tests/testthat/test-sprintf_linter.R
  tests/testthat/test-strings_as_factors_linter.R
Labels: documentation

#1680 Split S3 and S4 linters (and tests) into their own files
  DESCRIPTION
  R/expect_s3_class_linter.R
  R/expect_s4_class_linter.R
  man/expect_s3_class_linter.Rd
  man/expect_s4_class_linter.Rd
  tests/testthat/test-expect_s3_class_linter.R
  tests/testthat/test-expect_s4_class.R
Labels: internals

#1688 Add examples to documentation: Part-9 (cleanup)
  NEWS.md
  R/assignment_linter.R
  R/class_equals_linter.R
  R/condition_message_linter.R
  R/conjunct_test_linter.R
  R/expect_named_linter.R
  R/expect_s3_class_linter.R
  R/expect_s4_class_linter.R
  R/expect_type_linter.R
  R/extraction_operator_linter.R
  R/fixed_regex_linter.R
  R/is_numeric_linter.R
  R/missing_argument_linter.R
  R/nested_ifelse_linter.R
  R/package_hooks_linter.R
  R/path_linters.R
  R/sprintf_linter.R
  man/absolute_path_linter.Rd
  man/assignment_linter.Rd
  man/class_equals_linter.Rd
  man/condition_message_linter.Rd
  man/conjunct_test_linter.Rd
  man/expect_named_linter.Rd
  man/expect_s3_class_linter.Rd
  man/expect_s4_class_linter.Rd
  man/expect_type_linter.Rd
  man/extraction_operator_linter.Rd
  man/fixed_regex_linter.Rd
  man/is_numeric_linter.Rd
  man/missing_argument_linter.Rd
  man/nested_ifelse_linter.Rd
  man/nonportable_path_linter.Rd
  man/package_hooks_linter.Rd
  man/sprintf_linter.Rd
Labels: documentation

#1693 use parameterized test on public API for implicit_integer_linter()
  tests/testthat/test-implicit_integer_linter.R
Labels: internals, testing

#1720 Use public interface to test internal functions: Part-1
  tests/testthat/test-exclusions.R
  tests/testthat/test-expect_lint.R
  tests/testthat/test-utils.R
Labels: testing

#1732 Print the code in `indentation_linter()` examples
  R/indentation_linter.R
  man/indentation_linter.Rd
Labels: documentation
