Repository r-lib/lintr, pull requests merged in 2022-12, with the labels that each got.

#1528 Add sort_linter()
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/sort_linter.R
  inst/lintr/linters.csv
  man/best_practices_linters.Rd
  man/efficiency_linters.Rd
  man/linters.Rd
  man/readability_linters.Rd
  man/sort_linter.Rd
  tests/testthat/test-sort_linter.R
Labels: new-linter

#1814 Implement `implicit_assignment_linter()`
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/implicit_assignment_linter.R
  inst/lintr/linters.csv
  man/best_practices_linters.Rd
  man/configurable_linters.Rd
  man/implicit_assignment_linter.Rd
  man/linters.Rd
  man/readability_linters.Rd
  man/style_linters.Rd
  tests/testthat/test-implicit_assignment_linter.R
Labels: new-linter

#1821 Add tests for multi-line anonymous functions for `implicit_assignment_linter()`
  tests/testthat/test-implicit_assignment_linter.R
Labels: testing

#1828 More tests for `brace_linter()` with pipes and formula syntax
  tests/testthat/test-brace_linter.R
Labels: testing

#1840 Allow `except = NULL` to remove all exceptions in `implicit_assignment_linter()`
  R/implicit_assignment_linter.R
  tests/testthat/test-implicit_assignment_linter.R
Labels: feature

#1856 Consistently use Markdown lists with seealso tags
  R/T_and_F_symbol_linter.R
  R/absolute_path_linter.R
  R/assignment_linter.R
  R/brace_linter.R
  R/commas_linter.R
  R/expect_s3_class_linter.R
  R/expect_s4_class_linter.R
  R/function_argument_linter.R
  R/function_left_parentheses_linter.R
  R/infix_spaces_linter.R
  R/line_length_linter.R
  R/nonportable_path_linter.R
  R/paren_body_linter.R
  R/pipe_continuation_linter.R
  R/redundant_equals_linter.R
  R/routine_registration_linter.R
  R/semicolon_linter.R
  R/single_quotes_linter.R
  R/spaces_inside_linter.R
  R/spaces_left_parentheses_linter.R
  R/vector_logic_linter.R
  man/T_and_F_symbol_linter.Rd
  man/absolute_path_linter.Rd
  man/assignment_linter.Rd
  man/brace_linter.Rd
  man/commas_linter.Rd
  man/expect_s3_class_linter.Rd
  man/expect_s4_class_linter.Rd
  man/function_argument_linter.Rd
  man/function_left_parentheses_linter.Rd
  man/infix_spaces_linter.Rd
  man/line_length_linter.Rd
  man/nonportable_path_linter.Rd
  man/paren_body_linter.Rd
  man/pipe_continuation_linter.Rd
  man/redundant_equals_linter.Rd
  man/routine_registration_linter.Rd
  man/semicolon_linter.Rd
  man/single_quotes_linter.Rd
  man/spaces_inside_linter.Rd
  man/spaces_left_parentheses_linter.Rd
  man/vector_logic_linter.Rd
Labels: documentation

#1839 Use braces in `tryCatch()` calls
  R/get_source_expressions.R
Labels: internals

#1862 Deprecate `unnecessary_concatenation_linter()`
  .lintr_new
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/empty_assignment_linter.R
  R/linter_tags.R
  R/lintr-deprecated.R
  R/unnecessary_concatenation_linter.R
  inst/lintr/linters.csv
  man/available_linters.Rd
  man/configurable_linters.Rd
  man/deprecated_linters.Rd
  man/efficiency_linters.Rd
  man/empty_assignment_linter.Rd
  man/linters.Rd
  man/linters_with_tags.Rd
  man/lintr-deprecated.Rd
  man/readability_linters.Rd
  man/style_linters.Rd
  man/unnecessary_concatenation_linter.Rd
  tests/testthat/test-unnecessary_concatenation_linter.R
  tests/testthat/test-unneeded_concatenation_linter.R
Labels: consistency :apple: :green_apple:

#1857 Start fresh session each time in RStudio
  lintr.Rproj
Labels: internals

#1860 Improve formatting for `fixed_regrex_linter()` tests
  tests/testthat/test-fixed_regex_linter.R
Labels: internals

#1854 Implement `all_linters()` wrapper to access all available linters
  NAMESPACE
  NEWS.md
  R/use_lintr.R
  R/with.R
  README.md
  man/all_linters.Rd
  man/linters_with_defaults.Rd
  man/linters_with_tags.Rd
  man/modify_defaults.Rd
  tests/testthat/test-with.R
  vignettes/lintr.Rmd
Labels: feature

#1838 Additional test for `unnecessary_placeholder_linter()`
  tests/testthat/test-unnecessary_placeholder_linter.R
Labels: testing

#1864 Remove redundant nocov annotations in addins file
  R/addins.R
Labels: internals

#1834 Tests for multiple lints in `unnecessary_nested_if_linter()`
  tests/testthat/test-unnecessary_nested_if_linter.R
Labels: testing

#1865 Avoid implicit type coercion in conditional expressions using `length()`
  R/duplicate_argument_linter.R
  R/extract.R
  R/indentation_linter.R
  R/methods.R
Labels: internals

#1833 Tests for multiple lints in `implicit_assignment_linter()`
  tests/testthat/test-implicit_assignment_linter.R
Labels: testing

#1804 Add document on how to get help
  .github/SUPPORT.md
Labels: documentation
