Repository r-lib/lintr, pull requests merged in 2023-12, with the labels that each got.

#2395 Use `{testthat}` for mock testing
  DESCRIPTION
  R/lintr-package.R
  tests/testthat/test-cache.R
  tests/testthat/test-ci.R
  tests/testthat/test-methods.R
  tests/testthat/test-rstudio_markers.R
  tests/testthat/test-with.R
Labels: internals, testing

#2321 New allow_implicit_else argument for return_linter
  NEWS.md
  R/return_linter.R
  man/return_linter.Rd
  tests/testthat/test-return_linter.R
Labels: google-linters

#2373 Reduce duplication for maintaining docs of undesirable functions/operators
  R/zzz.R
  man/default_undesirable_functions.Rd
Labels: documentation

#2498 Remove reference to deprecated function from examples
  R/unnecessary_nesting_linter.R
  man/unnecessary_nesting_linter.Rd
Labels: documentation
