Repository r-lib/lintr, pull requests merged in 2024-06, with the labels that each got.

#2593 Use public interface to test `logical_env()`
  tests/testthat/test-ci.R
  tests/testthat/test-settings.R
Labels: internals, testing

#2411 Handle comparison to negative non-integer in expect_identical_linter
  NEWS.md
  R/expect_identical_linter.R
  tests/testthat/test-expect_identical_linter.R
Labels: feature

#2597 Remove usage of internal function in CI tests
  R/make_linter_from_regex.R
  tests/testthat/test-ci.R
Labels: internals

#2418 Use `{cli}` for formatting condition messages
  .lintr
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/addins.R
  R/backport_linter.R
  R/cache.R
  R/exclude.R
  R/expect_lint.R
  R/extract.R
  R/lint.R
  R/linter_tags.R
  R/lintr-package.R
  R/namespace_linter.R
  R/object_name_linter.R
  R/object_overwrite_linter.R
  R/object_usage_linter.R
  R/path_utils.R
  R/semicolon_linter.R
  R/settings.R
  R/shared_constants.R
  R/tree_utils.R
  R/undesirable_function_linter.R
  R/undesirable_operator_linter.R
  R/use_lintr.R
  R/utils.R
  R/with.R
  R/xml_nodes_to_lints.R
  R/xp_utils.R
  man/expect_lint_free.Rd
  tests/testthat/test-Lint-builder.R
  tests/testthat/test-backport_linter.R
  tests/testthat/test-exclusions.R
  tests/testthat/test-expect_lint.R
  tests/testthat/test-library_call_linter.R
  tests/testthat/test-lint.R
  tests/testthat/test-lint_dir.R
  tests/testthat/test-linter_tags.R
  tests/testthat/test-normalize_exclusions.R
  tests/testthat/test-parse_exclusions.R
  tests/testthat/test-semicolon_linter.R
  tests/testthat/test-settings.R
  tests/testthat/test-undesirable_function_linter.R
  tests/testthat/test-undesirable_operator_linter.R
  tests/testthat/test-unnecessary_concatenation_linter.R
  tests/testthat/test-with.R
  tests/testthat/test-xml_nodes_to_lints.R
  tests/testthat/test-xp_utils.R
Labels: feature
